# Intensifyer docker-compose!
# 2021-03-13

services:
  intensifyer:
    build:
      context: '.'
    container_name: bot_intensifyer
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:5000/health']
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    stop_grace_period: '${DOCKER_STOP_GRACE_PERIOD:-3s}'
    volumes:
      - ./images:/home/intensifyer/images
      - ./logs:/home/intensifyer/logs

volumes:
  images:
